Frontend [new Draft]
openaudiosearch/repco-specs pull request #35
Opened 2022-11-15 15:22 UTC by nemi-notrace

This is a new draft including radix-ui

2022-11-22 13:31 UTC, dryptomim commented on packages/repco-frontend/app/lib/helpers.tsx
> +  console.log('SET')
remove debug logs

2022-11-22 13:45 UTC, dryptomim requested changes

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/lib/helpers.tsx
> +  console.log('get')
remove debug logs

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/routes/$playlists/add.tsx
> +  console.log(uid, playlistAndUid)
remove debug logs

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/routes/$playlists/add.tsx
> +  }, [playlistAndUid, uid])
i think you can simplify this and dont have to use two useEffect hooks

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/routes/$playlists/playlist/$id.tsx
> +  console.log(data)
remove debug logs

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/routes/$playlists/playlist/$id.tsx
> +  console.log(data)
remove debug logs

2022-11-22 13:45 UTC, dryptomim commented on packages/repco-frontend/app/routes/playlists.tsx
> +import type { ActionFunction, LoaderFunction } from '@remix-run/node'
move some parts of this page to /$playlists/index and just leave the shared parts here and use the outlet-component

2022-12-14 09:47 UTC, Frando commented
Closing in favor of #38

2022-12-14 09:47 UTC, closed without merging